export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN'
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS'
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR'


export const LOGOUT_USER = 'LOGOUT_USER'

export const UPLOAD_IMAGE="UPLOAD_IMAGE"

export const UPLOAD_IMAGE_REGISTER="UPLOAD_IMAGE_REGISTER"

export const HANDLE_CHANGE="HANDLE_CHANGE"

export const CLEAR_UPLOADS="CLEAR_UPLOADS"


export const CHANGE_PAGE="CHANGE_PAGE"


export const SUBMIT_PIN_BEGIN="SUBMIT_PIN_BEGIN"
export const SUBMIT_PIN_SUCCESS="SUBMIT_PIN_SUCCESS"
export const SUBMIT_PIN_ERROR="SUBMIT_PIN_ERROR"

export const DELETE_VEDIO="DELETE_VEDIO"

export const CHANGE_FILTER_CATEGORY=" CHANGE_FILTER_CATEGORY"

export const GET_ALL_PINS="GET_ALL_PINS"

export const GET_CURRENT_USER__PINS="GET_CURRENT_USER_PINS"

export const GET_SINGLE_USER_PINS="GET_SINGLE_USER_PINS"

export const SUBMIT_REVIEW_BEGIN=" SUBMIT_REVIEW_BEGIN"
export const SUBMIT_REVIEW_SUCCESS=" SUBMIT_REVIEW_SUCCESS"
export const SUBMIT_REVIEW_ERROR=" SUBMIT_REVIEW_ERROR"

export const SINGLE_PIN_REVIEWS="SINGLE_PIN_REVIEWS"

export const SINGLE_PIN_SINGLE_USER_LIKED_STATUS="SINGLE_PIN_SINGLE_USER_LIKED_STATUS"

export const SINGLE_PIN_LIKED_NUMBER="SINGLE_PIN_LIKED_NUMBER"

export const CURRENT_USER_LIKED_PINS=" CURRENT_USER_LIKED_PINS"

export const SINGLE_USER_LIKED_PINS="SINGLE_USER_LIKED_PINS"






